SELECT SupplierID,
        SupplierName,
        SupplierCategoryID,
        PrimaryContactPersonID,
        AlternateContactPersonID,
        DeliveryMethodID,
        DeliveryCityID,
        PostalCityID,
        SupplierReference,
        BankAccountName,
        BankAccountBranch,
        BankAccountCode,
        BankAccountNumber,
        BankInternationalCode,
        PaymentDays,
        InternalComments,
        PhoneNumber,
        FaxNumber,
        WebsiteURL,
        DeliveryAddressLine1,
        DeliveryAddressLine2,
        DeliveryPostalCode,
        CAST(DeliveryLocation AS varchar(100)) AS DeliveryLocation,
        PostalAddressLine1,
        PostalAddressLine2,
        PostalPostalCode,
        LastEditedBy,
        ValidFrom,
        ValidTo
    FROM Purchasing.Suppliers
UNION
SELECT SupplierID,
        SupplierName,
        SupplierCategoryID,
        PrimaryContactPersonID,
        AlternateContactPersonID,
        DeliveryMethodID,
        DeliveryCityID,
        PostalCityID,
        SupplierReference,
        BankAccountName,
        BankAccountBranch,
        BankAccountCode,
        BankAccountNumber,
        BankInternationalCode,
        PaymentDays,
        InternalComments,
        PhoneNumber,
        FaxNumber,
        WebsiteURL,
        DeliveryAddressLine1,
        DeliveryAddressLine2,
        DeliveryPostalCode,
        CAST(DeliveryLocation AS varchar(100)) AS DeliveryLocation,
        PostalAddressLine1,
        PostalAddressLine2,
        PostalPostalCode,
        LastEditedBy,
        ValidFrom,
        ValidTo
    FROM Purchasing.Suppliers_Archive

