SELECT InvoiceID,
        CustomerID,
        BillToCustomerID,
        OrderID,
        DeliveryMethodID,
        ContactPersonID,
        AccountsPersonID,
        SalespersonPersonID,
        PackedByPersonID,
        InvoiceDate,
        CustomerPurchaseOrderNumber,
        IsCreditNote,
        CreditNoteReason,
        Comments,
        DeliveryInstructions,
        InternalComments,
        TotalDryItems,
        TotalChillerItems,
        DeliveryRun,
        RunPosition,
        ReturnedDeliveryData,
        ConfirmedDeliveryTime,
        ConfirmedReceivedBy,
        LastEditedBy,
        LastEditedWhen
    FROM Sales.Invoices