SELECT OrderID,
            CustomerID,
            SalespersonPersonID,
            PickedByPersonID,
            ContactPersonID,
            BackorderOrderID,
            OrderDate,
            ExpectedDeliveryDate,
            CustomerPurchaseOrderNumber,
            IsUndersupplyBackordered,
            Comments,
            DeliveryInstructions,
            InternalComments,
            PickingCompletedWhen,
            LastEditedBy,
            LastEditedWhen
      FROM Sales.Orders