name: 'Deploy Microsoft WWI packages to Databricks'

on:
    workflow_dispatch:
      inputs:
        cluster_id:
          description: 'Optionaly overwrite job cluster'
          required: false
          type: string
          default: ''

jobs:
  deploy:
    name: "Build and Deploy Bundle to the Workspaces"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pip install poetry

      # Download the Databricks CLI.
      # See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      - name: Validation 
        run: |
          databricks bundle validate
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

      # Deploy the bundle to the "qa" target as defined
      # in the bundle's settings file.
      - name: Deploy with custom cluster
        if: ${{ github.event.inputs.cluster_id != '' }}
        run: |
          databricks bundle deploy -c ${{ github.event.inputs.cluster_id }}
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

      - name: Deploy with default cluster
        if: ${{ github.event.inputs.cluster_id == '' }}
        run: |
          databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: dev

